#!/usr/bin/env python3

from __future__ import annotations

import json
from pathlib import Path

from bidrisk import bidrisk_pb2
from google.protobuf.timestamp_pb2 import Timestamp

_REPO_ROOT = Path(__file__).resolve().parents[3]

GOLDEN_DIR = _REPO_ROOT / "tests" / "contract" / "golden"

WRITER = Path(__file__).resolve().relative_to(_REPO_ROOT).as_posix()

PLACED_AT_SECONDS = 1_786_000_496
PLACED_AT_NANOS = 500_000_000

REASONS = ["bid is 3.0× the current price", "account is 2 days old"]
MODEL_VERSION = "bidrisk-golden"
REJECT_MESSAGE = "risk score 0.875 ≥ 0.70"


# Python writes these bytes and the C# test reads them back. That is the point: a C#
# writer read by a C# reader would only prove C# agrees with itself.
def risk_assessment() -> bidrisk_pb2.RiskAssessment:
    return bidrisk_pb2.RiskAssessment(
        score=0.875,
        level=bidrisk_pb2.RISK_LEVEL_HIGH,
        reasons=REASONS,
        inference_ms=1.25,
        model_version=MODEL_VERSION,
    )


def accepted_response() -> bidrisk_pb2.PlaceBidResponse:
    placed_at = Timestamp(seconds=PLACED_AT_SECONDS, nanos=PLACED_AT_NANOS)
    bid = bidrisk_pb2.Bid(
        id=4242,
        lot_id=42,
        bidder_id=7,
        amount=1234.5,
        placed_at=placed_at,
        risk_score=0.875,
        risk_level=bidrisk_pb2.RISK_LEVEL_HIGH,
        accepted=True,
        reject_reason=bidrisk_pb2.REJECT_REASON_UNSPECIFIED,
    )
    return bidrisk_pb2.PlaceBidResponse(
        accepted=bidrisk_pb2.BidAccepted(bid=bid, risk=risk_assessment())
    )


def rejected_response() -> bidrisk_pb2.PlaceBidResponse:
    return bidrisk_pb2.PlaceBidResponse(
        rejected=bidrisk_pb2.BidRejected(
            reason=bidrisk_pb2.REJECT_REASON_HIGH_RISK,
            message=REJECT_MESSAGE,
            risk=risk_assessment(),
        )
    )


EXPECTED: dict[str, object] = {
    "_comment": f"Generated by {WRITER} — run `make golden` to refresh.",
    "risk": {
        "score": 0.875,
        "level": "RISK_LEVEL_HIGH",
        "level_number": int(bidrisk_pb2.RISK_LEVEL_HIGH),
        "reasons": REASONS,
        "inference_ms": 1.25,
        "model_version": MODEL_VERSION,
    },
    "accepted": {
        "outcome_case": "accepted",
        "bid": {
            "id": 4242,
            "lot_id": 42,
            "bidder_id": 7,
            "amount": 1234.5,
            "placed_at_seconds": PLACED_AT_SECONDS,
            "placed_at_nanos": PLACED_AT_NANOS,
            "risk_score": 0.875,
            "risk_level": "RISK_LEVEL_HIGH",
            "accepted": True,
            "reject_reason": "REJECT_REASON_UNSPECIFIED",
        },
    },
    "rejected": {
        "outcome_case": "rejected",
        "reason": "REJECT_REASON_HIGH_RISK",
        "reason_number": int(bidrisk_pb2.REJECT_REASON_HIGH_RISK),
        "message": REJECT_MESSAGE,
    },
}


def main() -> None:
    GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for name, message in (
        ("accepted.bin", accepted_response()),
        ("rejected.bin", rejected_response()),
    ):
        path = GOLDEN_DIR / name
        path.write_bytes(message.SerializeToString(deterministic=True))
        written.append(f"{name} ({path.stat().st_size} bytes)")

    (GOLDEN_DIR / "expected.json").write_text(
        json.dumps(EXPECTED, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print("✓ golden files: " + " · ".join(written) + " · expected.json")


if __name__ == "__main__":
    main()
