#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
import json
import os
import re
from datetime import UTC, datetime
from pathlib import Path

import numpy as np
import numpy.typing as npt
from sklearn.metrics import (
    accuracy_score,
    brier_score_loss,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split

from bidrisk_ml.features import FEATURE_NAMES, extract_matrix
from bidrisk_ml.model import build_pipeline, save_artifact
from bidrisk_ml.synth import from_csv_row

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DATA = REPO_ROOT / "data" / "synthetic_bids.csv"
DEFAULT_OUT = REPO_ROOT / "models" / "bidrisk.joblib"
DEFAULT_METRICS = REPO_ROOT / "models" / "metrics.json"
README = REPO_ROOT / "README.md"

THRESHOLD_SWEEP = (0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90)

TARGET_PRECISION = 0.94

CALIBRATION_TOLERANCE = 0.15


def load_dataset(path: Path) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.int64]]:
    with path.open(newline="", encoding="utf-8") as fh:
        rows = [from_csv_row(r) for r in csv.DictReader(fh)]
    if not rows:
        raise SystemExit(f"no rows in {path} — run generate.py first")
    x = extract_matrix([r.facts for r in rows])
    y = np.asarray([r.is_suspicious for r in rows], dtype=np.int64)
    return x, y


def scores_at(
    threshold: float, y_true: npt.NDArray[np.int64], proba: npt.NDArray[np.float64]
) -> dict[str, float]:
    predicted = (proba >= threshold).astype(np.int64)
    return {
        "threshold": round(threshold, 2),
        "accuracy": round(float(accuracy_score(y_true, predicted)), 4),
        "precision": round(float(precision_score(y_true, predicted, zero_division=0)), 4),
        "recall": round(float(recall_score(y_true, predicted, zero_division=0)), 4),
        "flagged": int(predicted.sum()),
    }


def calibration(y_true: npt.NDArray[np.int64], proba: npt.NDArray[np.float64]) -> dict[str, float]:
    base_rate = float(y_true.mean())
    mean_predicted = float(proba.mean())
    return {
        "base_rate": round(base_rate, 4),
        "mean_predicted": round(mean_predicted, 4),
        "ratio": round(mean_predicted / base_rate, 3),
        "brier": round(float(brier_score_loss(y_true, proba)), 4),
    }


def pick_threshold(
    y_true: npt.NDArray[np.int64], proba: npt.NDArray[np.float64], target: float
) -> float:
    best = 0.99
    for step in range(5, 100):
        t = step / 100.0
        predicted = (proba >= t).astype(np.int64)
        if predicted.sum() == 0:
            break
        if precision_score(y_true, predicted, zero_division=0) >= target:
            best = t
            break
    return best


def render_markdown(metrics: dict[str, object]) -> str:
    op = metrics["operating_point"]
    assert isinstance(op, dict)
    sweep = metrics["threshold_sweep"]
    assert isinstance(sweep, list)
    cal = metrics["calibration"]
    assert isinstance(cal, dict)

    lines = [
        f"Trained on **{metrics['n_train']} bids**, evaluated on a held-out "
        f"**{metrics['n_test']}** ({metrics['suspicious_share_test']:.1%} suspicious). "
        f"Model: {metrics['model']}.",
        "",
        f"At the threshold the service actually rejects on (**{op['threshold']}**):",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Accuracy | **{op['accuracy']:.3f}** |",
        f"| Precision | **{op['precision']:.3f}** |",
        f"| Recall | **{op['recall']:.3f}** |",
        f"| ROC AUC | {metrics['roc_auc']:.3f} |",
        "",
        f"**The score is a probability, not just a ranking.** Mean predicted "
        f"{cal['mean_predicted']:.3f} against a true rate of {cal['base_rate']:.3f}, Brier "
        f"{cal['brier']:.4f}. That holds because the model is fitted on the real class balance — "
        "`class_weight='balanced'` would inflate every score. Imbalance is handled at the "
        "threshold instead.",
        "",
        "**Precision matters most here.** A false positive rejects a real bidder's money in real "
        "time; a false negative stores a suspicious bid with its score, which can be reviewed "
        "later. So the threshold trades recall away to keep precision up.",
        "",
        "How that trade-off moves with the threshold:",
        "",
        "| Threshold | Precision | Recall | Bids flagged |",
        "|---|---|---|---|",
    ]
    for row in sweep:
        assert isinstance(row, dict)
        lines.append(
            f"| {row['threshold']:.2f} | {row['precision']:.3f} "
            f"| {row['recall']:.3f} | {row['flagged']} |"
        )
    lines += [
        "",
        f"<sub>Generated by `make train` on {metrics['trained_at']} · model version "
        f"`{metrics['model_version']}` · do not edit by hand.</sub>",
    ]
    return "\n".join(lines)


def update_readme(markdown: str) -> bool:
    if not README.exists():
        return False
    text = README.read_text(encoding="utf-8")
    pattern = re.compile(r"(<!-- METRICS -->)(.*?)(<!-- /METRICS -->)", re.DOTALL)
    if not pattern.search(text):
        return False
    README.write_text(
        pattern.sub(lambda m: f"{m.group(1)}\n\n{markdown}\n\n{m.group(3)}", text), encoding="utf-8"
    )
    return True


# Offline build step. The service only ever loads the file this writes.
def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, default=DEFAULT_DATA)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--metrics", type=Path, default=DEFAULT_METRICS)
    parser.add_argument("--seed", type=int, default=int(os.getenv("TRAIN_SEED", "42")))
    parser.add_argument(
        "--threshold", type=float, default=float(os.getenv("RISK_REJECT_THRESHOLD", "0.70"))
    )
    args = parser.parse_args()

    x, y = load_dataset(args.data)
    x_train, x_test, y_train, y_test = train_test_split(
        x, y, test_size=0.2, random_state=args.seed, stratify=y
    )

    pipeline = build_pipeline(args.seed)
    pipeline.fit(x_train, y_train)

    proba = pipeline.predict_proba(x_test)[:, 1]
    operating = scores_at(args.threshold, y_test, proba)
    trained_at = datetime.now(UTC).replace(microsecond=0)
    model_version = f"bidrisk-{trained_at:%Y%m%d%H%M%S}"

    coefficients_by_name = {
        name: round(float(c), 4)
        for name, c in zip(FEATURE_NAMES, pipeline.named_steps["model"].coef_[0], strict=True)
    }
    calib = calibration(y_test, proba)
    metrics: dict[str, object] = {
        "model": "LogisticRegression on standardised features, fitted on the true class balance",
        "model_version": model_version,
        "trained_at": trained_at.isoformat(),
        "seed": args.seed,
        "n_train": int(len(y_train)),
        "n_test": int(len(y_test)),
        "suspicious_share_test": round(float(y_test.mean()), 4),
        "roc_auc": round(float(roc_auc_score(y_test, proba)), 4),
        "calibration": calib,
        "suggested_threshold": pick_threshold(y_test, proba, TARGET_PRECISION),
        "target_precision": TARGET_PRECISION,
        "operating_point": operating,
        "threshold_sweep": [scores_at(t, y_test, proba) for t in THRESHOLD_SWEEP],
        "feature_names": list(FEATURE_NAMES),
        "coefficients": coefficients_by_name,
    }

    save_artifact(
        path=args.out,
        pipeline=pipeline,
        model_version=model_version,
        trained_at=trained_at.isoformat(),
        reject_threshold=args.threshold,
        metrics=metrics,
    )
    args.metrics.parent.mkdir(parents=True, exist_ok=True)
    args.metrics.write_text(json.dumps(metrics, indent=2) + "\n", encoding="utf-8")

    print(f"✓ model    → {args.out}  ({model_version})")
    print(f"✓ metrics  → {args.metrics}")
    print(
        f"  at threshold {operating['threshold']}: "
        f"accuracy {operating['accuracy']:.3f} · "
        f"precision {operating['precision']:.3f} · "
        f"recall {operating['recall']:.3f} · roc_auc {metrics['roc_auc']:.3f}"
    )
    print("  coefficients: " + " · ".join(f"{n}={c:+.2f}" for n, c in coefficients_by_name.items()))
    print(
        f"  calibration: mean predicted {calib['mean_predicted']:.3f} vs true rate "
        f"{calib['base_rate']:.3f} ({calib['ratio']:.2f}×) · brier {calib['brier']:.4f}"
    )
    if abs(calib["ratio"] - 1.0) > CALIBRATION_TOLERANCE:
        raise SystemExit(
            f"the model is not calibrated: it predicts {calib['ratio']:.2f}× the true rate of "
            "suspicious bids, so its output is a ranking score, not a probability, and the "
            "reject threshold does not mean what the README says it means."
        )
    suggested = pick_threshold(y_test, proba, TARGET_PRECISION)
    if abs(suggested - args.threshold) > 0.005:
        print(
            f"  note: {suggested} is the lowest threshold reaching precision "
            f"{TARGET_PRECISION}; the service is configured for {args.threshold}"
        )
    if update_readme(render_markdown(metrics)):
        print("✓ README   → metrics section updated")


if __name__ == "__main__":
    main()
